### ISSUE TITLE
使用hyperf-ext/jwt无法创建token

### ISSUE THREAD

**Issue by cywan** [hyperf-ext/auth#3]
![image](https://user-images.githubusercontent.com/26513205/100308299-0604ed80-2fe3-11eb-9b59-69046540e4ca.png)

**Comment by cywan** [comment]
![image](https://user-images.githubusercontent.com/26513205/100308484-7ad82780-2fe3-11eb-948e-199202ab7342.png)
![image](https://user-images.githubusercontent.com/26513205/100308506-8592bc80-2fe3-11eb-8b6c-60082cb17306.png)
![image](https://user-images.githubusercontent.com/26513205/100308517-8cb9ca80-2fe3-11eb-9678-e050798e1372.png)
![image](https://user-images.githubusercontent.com/26513205/100308525-92afab80-2fe3-11eb-88c2-db42462fc0cc.png)
![image](https://user-images.githubusercontent.com/26513205/100308535-9ba07d00-2fe3-11eb-9b88-d17212bb5856.png)
![image](https://user-images.githubusercontent.com/26513205/100308540-a0fdc780-2fe3-11eb-8d82-fb7bf2febb5a.png)
![image](https://user-images.githubusercontent.com/26513205/100308559-a9ee9900-2fe3-11eb-93ef-d99bdd6e37f0.png)
![image](https://user-images.githubusercontent.com/26513205/100308574-b07d1080-2fe3-11eb-87fb-71f14777ed27.png)

**Comment by ericyzhu** [comment]
依赖的 lcobucci/jwt 在 3.4 版本进行了一些破坏性更新以过渡到 4.0，目前发布了一个小版本来通过锁定版本号到 ~3.3.0 避免这些问题。
