### ISSUE TITLE
composer require hyperf-ext/auth安装出错

### ISSUE THREAD

**Issue by hq22** [hyperf-ext/auth#9]
Using version ^2.1 for hyperf-ext/auth
./composer.json has been updated
Running composer update hyperf-ext/auth
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires hyperf-ext/auth ^2.1 -> satisfiable by hyperf-ext/auth[v2.1.0].
    - hyperf-ext/auth v2.1.0 requires hyperf/command ~2.1.0 -> found hyperf/command[v2.1.0-beta1, v2.1.0, 2.1.x-dev] but it conflicts with your root composer.json require (~2.2.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by ericyzhu** [comment]
已支持hyperf2.2
